name: 'pacc_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'pacc_dbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  pacc_dbt:
    staging:
      +database: "{{ 'analytics-prod' if target.name == 'prod' else 'analytics-dev' }}"

    int:
      +materialized: ephemeral
      +database: "{{ 'analytics-prod' if target.name == 'prod' else 'analytics-dev' }}"
      metrics:
        +materialized: table
        
    marts:
      +database: "{{ 'analytics-prod' if target.name == 'prod' else 'analytics-dev' }}"
      accounting:
        +materialized: table
      commercial:
        +materialized: table
      human_resources:
        +materialized: table
      marketing:
        +materialized: table
      metrics:
        +materialized: table
      supply_chain:
        +materialized: table
      cs:
        +materialized: table  


seeds:
  +database: "{{ 'analytics-prod' if target.name == 'prod' else 'analytics-dev' }}"