version: 2

models:
  - name: fct_order_line_items
    columns:
      - name: unique_id
        tests:
          - unique
          - not_null

  - name: fct_orders
    columns:
      - name: unique_id
        tests:
          - unique
          - not_null
      - name: tran_at
      - name: shift
      - name: bu
      - name: group_channel
      - name: net_sales
      - name: promotion
      - name: is_member_order_splited_bill
        description: '{{ doc("is_member_order_splited_bill") }}'